//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Horario.Domain.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HorarioEntities : DbContext
    {
        public HorarioEntities()
            : base("name=HorarioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Alumno> Alumnoes { get; set; }
        public virtual DbSet<Carrera> Carreras { get; set; }
        public virtual DbSet<Cita> Citas { get; set; }
        public virtual DbSet<Profesor> Profesors { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Visitante_Externo> Visitante_Externo { get; set; }
        public virtual DbSet<Citas_ComDica> Citas_ComDica { get; set; }
        public virtual DbSet<Com_Visitante> Com_Visitante { get; set; }
        public virtual DbSet<Horario_Dica> Horario_Dica { get; set; }
    }
}
